/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prog.tpi_colonia_felina_paii.vista;

import java.awt.Color;

public class InicioDeSesion extends javax.swing.JFrame {

    public InicioDeSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        bienvenida = new javax.swing.JLabel();
        labelNombreUsuario = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        nombreUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(197, 197, 197));
        bg.setForeground(new java.awt.Color(204, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Roboto Bk", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Gestión de Colonia Felina");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 610, -1));

        bienvenida.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bienvenida.setForeground(new java.awt.Color(102, 102, 102));
        bienvenida.setText("Bienvenido de nuevo. Por favor, introduce tus datos.");
        bg.add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 340, 40));

        labelNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        labelNombreUsuario.setText("Nombre de usuario");
        bg.add(labelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setText("********");
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordMousePressed(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        bg.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 390, -1));

        nombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setText("Introduce tu nombre de usuario");
        nombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreUsuarioMousePressed(evt);
            }
        });
        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });
        bg.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 390, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contraseña");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/huella.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 70, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(255, 112, 0));
        btnIniciarSesion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        bg.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 390, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioActionPerformed

    }//GEN-LAST:event_nombreUsuarioActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void nombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreUsuarioMousePressed
        if(nombreUsuario.getText().equals("Introduce tu nombre de usuario")){
            nombreUsuario.setText("");
            nombreUsuario.setForeground(Color.black);
        }
        if(String.valueOf(password.getPassword()).isEmpty()){
            password.setText("********");
            password.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nombreUsuarioMousePressed

    private void passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMousePressed
        if(String.valueOf(password.getPassword()).equals("********")){
            password.setText("");
            password.setForeground(Color.black);
        }
        if(nombreUsuario.getText().isEmpty()){
            nombreUsuario.setText("Introduce tu nombre de usuario");
            nombreUsuario.setForeground(Color.gray);            
        }
    }//GEN-LAST:event_passwordMousePressed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
